<template>
    <div data-role="page" id="people_phone_page">

        <tk-header :back="false">
            通讯录

        </tk-header>
            <tk-search v-model="searchVal"></tk-search>
            <tk-address-list @liClick="liClick" :filter="searchVal" v-model="list"></tk-address-list>
        
        
        <div id="page_footer3" class="page_footer smaller">
            <div class="jszx-bar-icon-up jszx-bar-item-4 ">
                <div>
                    <img src="/staitc/resources/images/icon_one.png" alt="">
                    <p>首页</p>
                </div>
                <div>
                    <img src="/staitc/resources/images/icon_two.png" alt="">
                    <p>公告</p>
                </div>
                <div>
                    <img src="/staitc/resources/images/icon_three_press.png" alt="">
                    <p style="color: #0283de;">通讯录</p>
                </div>
                <div>
                    <img src="/staitc/resources/images/icon_four.png" alt="">
                    <p>我的</p>
                </div>
            </div>
        </div>
    </div>
</template>

<script type="text/ecmascript-6">
    export default {
        name: "peoplePhone",
        data() {
            return {
                list:[],
                searchVal:''
            }
        },
        created() {

        },
        mounted() {

            var that=this;


                    $("#notice_welcome_list_html").empty();
                    app_noticeList(false, 1, $("#notice_welcome_list_inp").val(), window.noticeTypeList, "notice_welcome_list_html");



            // $("#people_phone_page").live("pageshow", function () {
            //首页
            $("#page_footer3").find(".jszx-bar-icon-up>div:eq(0)").listen("quickClick", function (e) {
                that.$router.push({path: 'welcome', query: {}});
            });
            //公告
            $("#page_footer3").find(".jszx-bar-icon-up>div:eq(1)").listen("quickClick", function (e) {
                that.$router.push({path: 'noticeWelcomeList', query: {}});
            });
            //通讯录
            $("#page_footer3").find(".jszx-bar-icon-up>div:eq(2)").listen("quickClick", function (e) {
                that.$router.push({path: 'peoplePhone', query: {}});
            });
            //我的
            $("#page_footer3").find(".jszx-bar-icon-up>div:eq(3)").listen("quickClick", function (e) {
                that.$router.push({path: 'moreWelcome', query: {}});
            });
            app_contactList3("", 0, 1, "");
            initPeoplePhone();
            //返回
            $("#people_phone_page .back-button").listen("quickClick", function (e) {
                // $.mobile.changePage("../load/welcome.html");
                that.$router.go(-1);
            });
            $(".sort_box").on("click", ".sort_list", function (e) {
                var phone = $(e.currentTarget).attr("mobile");
                var tel = $(e.currentTarget).attr("tel");
                var duty = $(e.currentTarget).attr("duty");
                var peoplename = $(e.currentTarget).attr("peoplename");

                window.phone = phone;
                window.tel = tel;
                window.duty = duty;
                window.peoplename = peoplename;
                // $.mobile.changePage("../phone/peopleDetail.html");
                that.$router.push('/peopleDetail');
            });

            //搜索
            $("#people_phone_page #people_phone_search").listen("quickClick", function (e) {
                window.conditionQuery = $("#people_phone_inp").val();
                app_contactList3("", 0, 2, window.conditionQuery);
            });

            // });

            function initPeoplePhone() {
                $("#people_phone_wrapper")[0].style.height = window.localInnerHeight - $("#people_phone_page .page_header").height() - $("#people_phone_page .page_footer").height();//- $("#people_phone_page .search_div").height() -$("#people_phone_page .page_footer").height() + "px";

                // initScroll({
                //     "wrapper": "people_phone_wrapper",
                //     "dir": "y",
                //     "bounce": false,
                //     "scrollBar": false
                // });
                window.info = '{"code":"0","datas":[{"deptName":"系统管理","userList":[{"phone":" ","tel":" ","id":"402880e92db726b5012db729f65f0001","userName":"系统管理员"}],"userCount":1,"id":"402880e92db5d2ee012db601b2220004"},{"deptName":"江苏省","userList":[],"userCount":0,"children":[{"children":[{"children":[{"children":[{"children":[{"id":"002002001001001001","text":"走访三级网格测试"}],"id":"002002001001001","text":"走访二级网格测试","state":"closed"}],"id":"002002001001","text":"丁岗镇(新能源产业园)","state":"closed"},{"id":"002002001002","text":"大路镇"},{"id":"002002001003","text":"姚桥镇"},{"id":"002002001004","text":"大港街道"},{"id":"002002001005","text":"丁卯街道(大学科技园)"}],"id":"002002001","text":"吴江平望","state":"closed"}],"id":"002002","text":"镇江市","state":"closed"}],"id":"8a8184b55b45f27c015b474e66520055"}]}';
                scrollToTop("people_phone_wrapper");

                $("#people_phone_inp").val("");

                window.conditionQuery = "";
                window.phone = "";
                window.tel = "";
                window.duty = "";
                window.peoplename = "";

            }

            function app_contactList3(deptId, type, flag, userName) {
                var obj = "";
                obj += toJson("pageNumber", 1) + "&";
                obj += toJson("pageSize", 200) + "&";//1顺级，2搜索
                obj += toJson("userName", userName);
                doPost("app_contactList3.action", obj, function (data) {

                    if (data.totalsize > 0) {

                        var array = data.datas;
                        //////////////////
                        that.list=data.datas.map(item=>{
                            return Object.assign({
                                id:item.dept_name,
                                name:item.display_name
                            },item)
                        })

                    } else {
                        toast(data.message);

                        var array = data.datas;
                        //////////////////
                        array = [
                            {
                                tel: 12345678,
                                mobile: 18066111900,
                                duty: 'my-duty',
                                display_name: '张政',
                                dept_name: '政务信息化应用事业部'
                            },
                            {
                                tel: 12345678,
                                mobile: 18066111900,
                                duty: 'my-duty',
                                display_name: '张三',
                                dept_name: '政务信息化应用事业部jjjhhh'
                            },
                            {
                                tel: 12345678,
                                mobile: 18066111900,
                                duty: 'my-duty',
                                display_name: '李四',
                                dept_name: 'abc政务信息化应用事业部'
                            },
                            {
                                tel: 12345678,
                                mobile: 18066111900,
                                duty: 'my-duty',
                                display_name: '王五1234',
                                dept_name: '政务信息化应用事业部1212'
                            }
                        ];
                        //////////////////
                      //  setPhone(array);
                    }
                }, "");
            }

            function setPhone(array) {
                var htmls = "";
                for (var i = 0; i < array.length; i++) {
                    var tel = "";
                    var mobile = "";
                    var duty = "";
                    var peoplename = "";
                    if (array[i].tel) {
                        tel = array[i].tel;
                    }
                    if (array[i].mobile) {
                        mobile = array[i].mobile;
                    }
                    if (array[i].duty) {
                        duty = array[i].duty;
                    }
                    if (array[i].display_name) {
                        peoplename = array[i].display_name;
                    }
                    htmls += '<div class="sort_list" tel="' + tel + '" mobile="' + mobile + '" duty="' + duty + '" peoplename="' + peoplename + '">';
                    htmls += '<div class="num_logo">';
                    //htmls+='(' + array[i].dept_name + ')';
                    htmls += '</div>';
                    htmls += '<div class="num_name">' + array[i].display_name + '(' + array[i].dept_name + ')</div>';
                    htmls += '</div>';
                    $(".sort_box").html(htmls);
                }
            }

            function initials() {//公众号排序
                var SortList = $(".sort_list");
                var SortBox = $(".sort_box");
                SortList.sort(asc_sort).appendTo('.sort_box');//按首字母排序
                function asc_sort(a, b) {
                    return makePy($(b).find('.num_name').text().charAt(0))[0].toUpperCase() < makePy($(a).find('.num_name').text().charAt(0))[0].toUpperCase() ? 1 : -1;
                }

                var initials = [];
                var num = 0;
                SortList.each(function (i) {
                    var initial = makePy($(this).find('.num_name').text().charAt(0))[0].toUpperCase();
                    if (initial >= 'A' && initial <= 'Z') {
                        if (initials.indexOf(initial) === -1)
                            initials.push(initial);
                    } else {
                        num++;
                    }
                });

                $.each(initials, function (index, value) {//添加首字母标签
                    SortBox.append('<div class="sort_letter" id="' + value + '">' + value + '</div>');
                });
                if (num != 0) {
                    SortBox.append('<div class="sort_letter" id="default">#</div>');
                }

                for (var i = 0; i < SortList.length; i++) {//插入到对应的首字母后面
                    var letter = makePy(SortList.eq(i).find('.num_name').text().charAt(0))[0].toUpperCase();
                    switch (letter) {
                        case "A":
                            $('#A').after(SortList.eq(i));
                            break;
                        case "B":
                            $('#B').after(SortList.eq(i));
                            break;
                        case "C":
                            $('#C').after(SortList.eq(i));
                            break;
                        case "D":
                            $('#D').after(SortList.eq(i));
                            break;
                        case "E":
                            $('#E').after(SortList.eq(i));
                            break;
                        case "F":
                            $('#F').after(SortList.eq(i));
                            break;
                        case "G":
                            $('#G').after(SortList.eq(i));
                            break;
                        case "H":
                            $('#H').after(SortList.eq(i));
                            break;
                        case "I":
                            $('#I').after(SortList.eq(i));
                            break;
                        case "J":
                            $('#J').after(SortList.eq(i));
                            break;
                        case "K":
                            $('#K').after(SortList.eq(i));
                            break;
                        case "L":
                            $('#L').after(SortList.eq(i));
                            break;
                        case "M":
                            $('#M').after(SortList.eq(i));
                            break;
                        case "O":
                            $('#O').after(SortList.eq(i));
                            break;
                        case "P":
                            $('#P').after(SortList.eq(i));
                            break;
                        case "Q":
                            $('#Q').after(SortList.eq(i));
                            break;
                        case "R":
                            $('#R').after(SortList.eq(i));
                            break;
                        case "S":
                            $('#S').after(SortList.eq(i));
                            break;
                        case "T":
                            $('#T').after(SortList.eq(i));
                            break;
                        case "U":
                            $('#U').after(SortList.eq(i));
                            break;
                        case "V":
                            $('#V').after(SortList.eq(i));
                            break;
                        case "W":
                            $('#W').after(SortList.eq(i));
                            break;
                        case "X":
                            $('#X').after(SortList.eq(i));
                            break;
                        case "Y":
                            $('#Y').after(SortList.eq(i));
                            break;
                        case "Z":
                            $('#Z').after(SortList.eq(i));
                            break;
                        default:
                            $('#default').after(SortList.eq(i));
                            break;
                    }
                }
            }

            var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
            var oMultiDiff = {
                "19969": "DZ",
                "19975": "WM",
                "19988": "QJ",
                "20048": "YL",
                "20056": "SC",
                "20060": "NM",
                "20094": "QG",
                "20127": "QJ",
                "20167": "QC",
                "20193": "YG",
                "20250": "KH",
                "20256": "ZC",
                "20282": "SC",
                "20285": "QJG",
                "20291": "TD",
                "20314": "YD",
                "20340": "NE",
                "20375": "TD",
                "20389": "YJ",
                "20391": "CZ",
                "20415": "PB",
                "20446": "YS",
                "20447": "SQ",
                "20504": "TC",
                "20608": "KG",
                "20854": "QJ",
                "20857": "ZC",
                "20911": "PF",
                "20504": "TC",
                "20608": "KG",
                "20854": "QJ",
                "20857": "ZC",
                "20911": "PF",
                "20985": "AW",
                "21032": "PB",
                "21048": "XQ",
                "21049": "SC",
                "21089": "YS",
                "21119": "JC",
                "21242": "SB",
                "21273": "SC",
                "21305": "YP",
                "21306": "QO",
                "21330": "ZC",
                "21333": "SDC",
                "21345": "QK",
                "21378": "CA",
                "21397": "SC",
                "21414": "XS",
                "21442": "SC",
                "21477": "JG",
                "21480": "TD",
                "21484": "ZS",
                "21494": "YX",
                "21505": "YX",
                "21512": "HG",
                "21523": "XH",
                "21537": "PB",
                "21542": "PF",
                "21549": "KH",
                "21571": "E",
                "21574": "DA",
                "21588": "TD",
                "21589": "O",
                "21618": "ZC",
                "21621": "KHA",
                "21632": "ZJ",
                "21654": "KG",
                "21679": "LKG",
                "21683": "KH",
                "21710": "A",
                "21719": "YH",
                "21734": "WOE",
                "21769": "A",
                "21780": "WN",
                "21804": "XH",
                "21834": "A",
                "21899": "ZD",
                "21903": "RN",
                "21908": "WO",
                "21939": "ZC",
                "21956": "SA",
                "21964": "YA",
                "21970": "TD",
                "22003": "A",
                "22031": "JG",
                "22040": "XS",
                "22060": "ZC",
                "22066": "ZC",
                "22079": "MH",
                "22129": "XJ",
                "22179": "XA",
                "22237": "NJ",
                "22244": "TD",
                "22280": "JQ",
                "22300": "YH",
                "22313": "XW",
                "22331": "YQ",
                "22343": "YJ",
                "22351": "PH",
                "22395": "DC",
                "22412": "TD",
                "22484": "PB",
                "22500": "PB",
                "22534": "ZD",
                "22549": "DH",
                "22561": "PB",
                "22612": "TD",
                "22771": "KQ",
                "22831": "HB",
                "22841": "JG",
                "22855": "QJ",
                "22865": "XQ",
                "23013": "ML",
                "23081": "WM",
                "23487": "SX",
                "23558": "QJ",
                "23561": "YW",
                "23586": "YW",
                "23614": "YW",
                "23615": "SN",
                "23631": "PB",
                "23646": "ZS",
                "23663": "ZT",
                "23673": "YG",
                "23762": "TD",
                "23769": "ZS",
                "23780": "QJ",
                "23884": "QK",
                "24055": "XH",
                "24113": "DC",
                "24162": "ZC",
                "24191": "GA",
                "24273": "QJ",
                "24324": "NL",
                "24377": "TD",
                "24378": "QJ",
                "24439": "PF",
                "24554": "ZS",
                "24683": "TD",
                "24694": "WE",
                "24733": "LK",
                "24925": "TN",
                "25094": "ZG",
                "25100": "XQ",
                "25103": "XH",
                "25153": "PB",
                "25170": "PB",
                "25179": "KG",
                "25203": "PB",
                "25240": "ZS",
                "25282": "FB",
                "25303": "NA",
                "25324": "KG",
                "25341": "ZY",
                "25373": "WZ",
                "25375": "XJ",
                "25384": "A",
                "25457": "A",
                "25528": "SD",
                "25530": "SC",
                "25552": "TD",
                "25774": "ZC",
                "25874": "ZC",
                "26044": "YW",
                "26080": "WM",
                "26292": "PB",
                "26333": "PB",
                "26355": "ZY",
                "26366": "CZ",
                "26397": "ZC",
                "26399": "QJ",
                "26415": "ZS",
                "26451": "SB",
                "26526": "ZC",
                "26552": "JG",
                "26561": "TD",
                "26588": "JG",
                "26597": "CZ",
                "26629": "ZS",
                "26638": "YL",
                "26646": "XQ",
                "26653": "KG",
                "26657": "XJ",
                "26727": "HG",
                "26894": "ZC",
                "26937": "ZS",
                "26946": "ZC",
                "26999": "KJ",
                "27099": "KJ",
                "27449": "YQ",
                "27481": "XS",
                "27542": "ZS",
                "27663": "ZS",
                "27748": "TS",
                "27784": "SC",
                "27788": "ZD",
                "27795": "TD",
                "27812": "O",
                "27850": "PB",
                "27852": "MB",
                "27895": "SL",
                "27898": "PL",
                "27973": "QJ",
                "27981": "KH",
                "27986": "HX",
                "27994": "XJ",
                "28044": "YC",
                "28065": "WG",
                "28177": "SM",
                "28267": "QJ",
                "28291": "KH",
                "28337": "ZQ",
                "28463": "TL",
                "28548": "DC",
                "28601": "TD",
                "28689": "PB",
                "28805": "JG",
                "28820": "QG",
                "28846": "PB",
                "28952": "TD",
                "28975": "ZC",
                "29100": "A",
                "29325": "QJ",
                "29575": "SL",
                "29602": "FB",
                "30010": "TD",
                "30044": "CX",
                "30058": "PF",
                "30091": "YSP",
                "30111": "YN",
                "30229": "XJ",
                "30427": "SC",
                "30465": "SX",
                "30631": "YQ",
                "30655": "QJ",
                "30684": "QJG",
                "30707": "SD",
                "30729": "XH",
                "30796": "LG",
                "30917": "PB",
                "31074": "NM",
                "31085": "JZ",
                "31109": "SC",
                "31181": "ZC",
                "31192": "MLB",
                "31293": "JQ",
                "31400": "YX",
                "31584": "YJ",
                "31896": "ZN",
                "31909": "ZY",
                "31995": "XJ",
                "32321": "PF",
                "32327": "ZY",
                "32418": "HG",
                "32420": "XQ",
                "32421": "HG",
                "32438": "LG",
                "32473": "GJ",
                "32488": "TD",
                "32521": "QJ",
                "32527": "PB",
                "32562": "ZSQ",
                "32564": "JZ",
                "32735": "ZD",
                "32793": "PB",
                "33071": "PF",
                "33098": "XL",
                "33100": "YA",
                "33152": "PB",
                "33261": "CX",
                "33324": "BP",
                "33333": "TD",
                "33406": "YA",
                "33426": "WM",
                "33432": "PB",
                "33445": "JG",
                "33486": "ZN",
                "33493": "TS",
                "33507": "QJ",
                "33540": "QJ",
                "33544": "ZC",
                "33564": "XQ",
                "33617": "YT",
                "33632": "QJ",
                "33636": "XH",
                "33637": "YX",
                "33694": "WG",
                "33705": "PF",
                "33728": "YW",
                "33882": "SR",
                "34067": "WM",
                "34074": "YW",
                "34121": "QJ",
                "34255": "ZC",
                "34259": "XL",
                "34425": "JH",
                "34430": "XH",
                "34485": "KH",
                "34503": "YS",
                "34532": "HG",
                "34552": "XS",
                "34558": "YE",
                "34593": "ZL",
                "34660": "YQ",
                "34892": "XH",
                "34928": "SC",
                "34999": "QJ",
                "35048": "PB",
                "35059": "SC",
                "35098": "ZC",
                "35203": "TQ",
                "35265": "JX",
                "35299": "JX",
                "35782": "SZ",
                "35828": "YS",
                "35830": "E",
                "35843": "TD",
                "35895": "YG",
                "35977": "MH",
                "36158": "JG",
                "36228": "QJ",
                "36426": "XQ",
                "36466": "DC",
                "36710": "JC",
                "36711": "ZYG",
                "36767": "PB",
                "36866": "SK",
                "36951": "YW",
                "37034": "YX",
                "37063": "XH",
                "37218": "ZC",
                "37325": "ZC",
                "38063": "PB",
                "38079": "TD",
                "38085": "QY",
                "38107": "DC",
                "38116": "TD",
                "38123": "YD",
                "38224": "HG",
                "38241": "XTC",
                "38271": "ZC",
                "38415": "YE",
                "38426": "KH",
                "38461": "YD",
                "38463": "AE",
                "38466": "PB",
                "38477": "XJ",
                "38518": "YT",
                "38551": "WK",
                "38585": "ZC",
                "38704": "XS",
                "38739": "LJ",
                "38761": "GJ",
                "38808": "SQ",
                "39048": "JG",
                "39049": "XJ",
                "39052": "HG",
                "39076": "CZ",
                "39271": "XT",
                "39534": "TD",
                "39552": "TD",
                "39584": "PB",
                "39647": "SB",
                "39730": "LG",
                "39748": "TPB",
                "40109": "ZQ",
                "40479": "ND",
                "40516": "HG",
                "40536": "HG",
                "40583": "QJ",
                "40765": "YQ",
                "40784": "QJ",
                "40840": "YK",
                "40863": "QJG"
            };

            function makePy(str) {
                if (typeof (str) != "string")
                    throw new Error(-1, "����makePy��Ҫ�ַ������Ͳ���!");
                var arrResult = new Array(); //�����м���������
                for (var i = 0, len = str.length; i < len; i++) {
                    var ch = str.charAt(i);
                    arrResult.push(checkCh(ch));
                }
                return mkRslt(arrResult);
            }

            function checkCh(ch) {
                var uni = ch.charCodeAt(0);

                if (uni > 40869 || uni < 19968)
                    return ch; //dealWithOthers(ch);
                return (oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
            }

            function mkRslt(arr) {
                var arrRslt = [""];
                for (var i = 0, len = arr.length; i < len; i++) {
                    var str = arr[i];
                    var strlen = str.length;
                    if (strlen == 1) {
                        for (var k = 0; k < arrRslt.length; k++) {
                            arrRslt[k] += str;
                        }
                    } else {
                        var tmpArr = arrRslt.slice(0);
                        arrRslt = [];
                        for (k = 0; k < strlen; k++) {
                            for (var j = 0; j < tmp.length; j++) {
                                tmp[j] += str.charAt(k);
                            }
                            arrRslt = arrRslt.concat(tmp);
                        }
                    }
                }
                return arrRslt;
            }
        },
        methods: {
            liClick(data){
                this.$router.push({
                    path:'/address-detail',
                    query:{
                        data
                    }
                })
            }
        }
    }
</script>

<style lang="less" >
    #people_phone_page .search_div {
        height: 3.2em;
        background: #edeef1;
    }

    #people_phone_page #people_phone_inp {
        width: 75%;
        float: left;
        margin-top: 0.5em;
    }

    #people_phone_page #people_phone_search {
        width: 4em;
        text-align: center;
        color: #ffffff;
        margin-top: 1em;
        float: right;
        line-height: 2.2em;
        border-radius: 0.3em;
    }

    #people_phone_page table tr td:first-child, #people_phone_page .page_content p {
        padding: 1em;
        text-align: left;
    }

    #people_phone_page table {
        margin-left: 0em;
    }

    #people_phone_page table tr td:last-child {
        padding-right: 1em;
        width: 2em;
    }

    #people_phone_page .page_content p {
        background: #f3f3f3;
    }

    #people_phone_page .phone_upback_img {
        width: 0.5em;
        padding: 0em 0.5em;
    }

    header.fixed {
        position: fixed;
        left: 0;
        top: 0;
        z-index: 99;
    }

    .header {
        margin: 0 20px;
        text-align: center;
        color: #4e4a49;
        font-size: 1em;
        height: 45px;
        line-height: 45px;
        position: relative;
    }

    #letter {
        width: 100px;
        height: 100px;
        border-radius: 5px;
        font-size: 75px;
        color: #555;
        text-align: center;
        line-height: 100px;
        background: rgba(145, 145, 145, 0.6);
        position: fixed;
        left: 50%;
        top: 50%;
        margin: -50px 0px 0px -50px;
        z-index: 99;
        display: none;
    }

    #letter img {
        width: 50px;
        height: 50px;
        float: left;
        margin: 25px 0px 0px 25px;
    }

    .sort_box {
        width: 100%;
        overflow: hidden;
    }

    .sort_list {
        padding: 10px 60px 10px 26px;
        position: relative;
        height: 40px;
        line-height: 40px;
        border-bottom: 1px solid #ddd;
    }

    .sort_list .num_logo {
        width: 80px;
        height: 50px;
        border-radius: 10px;
        overflow: hidden;
        position: absolute;
        top: 10px;
        left: 88px;
    }

    .sort_list .num_logo img {
        width: 50px;
        height: 50px;
    }

    .sort_list .num_name {
        color: #000;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .sort_letter {
        background-color: white;
        height: 30px;
        line-height: 30px;
        padding-left: 20px;
        color: #787878;
        font-size: 14px;
        border-bottom: 1px solid #ddd;
    }

    .initials {
        display: none;
        position: fixed;
        top: 47px;
        right: 0;
        height: 100%;
        width: 15px;
        padding-right: 10px;
        text-align: center;
        font-size: 12px;
        z-index: 99;
        background: rgba(145, 145, 145, 0);
    }

    .initials li img {
        width: 14px;
    }

    #page_footer3 {
        z-index: 999;
        position: fixed;
        bottom: 0px;
        width: 100%;
        height: 4em;
    }
</style>
